import { IsNotEmpty, IsString, IsMimeType } from 'class-validator';

/**
 * Data Transfer Object for requesting a signed upload URL.
 * The client sends this to get permission to upload.
 */
export class GetUploadUrlDto {
  @IsString()
  @IsNotEmpty()
  productId: string;

  @IsString()
  @IsNotEmpty()
  fileName: string;

  @IsString()
  @IsNotEmpty()
  @IsMimeType()
  fileType: string;
}

/**
 * Data Transfer Object for telling the server the upload is complete.
 * The client sends this after the direct upload to storage succeeds.
 */
export class FinalizeUploadBodyDto {
  @IsString()
  @IsNotEmpty()
  productId: string;

  @IsString()
  @IsNotEmpty()
  fileId: string; // The unique ID generated by the server in the previous step

  @IsString()
  @IsNotEmpty()
  path: string; // The storage path generated by the server in the previous step
}

/**
 * Data Transfer Object for validating the URL parameters
 * when deleting a product image.
 */
export class DeleteImageParamsDto {
  @IsString()
  @IsNotEmpty()
  productId: string;

  @IsString()
  @IsNotEmpty()
  imageId: string;
}