/**
 * Enterprise Queue Names
 * Centralized registry for all background processing domains.
 */
export enum QUEUES {
  NOTIFICATIONS = 'NOTIFICATIONS',
  ORDER_PROCESSING = 'ORDER_PROCESSING',
  PAYMENTS = 'PAYMENTS',
  BILLING = 'BILLING', // Dedicated to plan logic
  ANALYTICS = 'ANALYTICS',
  DATA_IMPORT = 'DATA_IMPORT',
  IMAGE_PROCESSING = 'IMAGE_PROCESSING',
}

/**
 * Job names within specific queues to keep workers organized.
 * SOLID Principle: Single Source of Truth for all background tasks.
 */
export enum JOB_NAMES {
  
  // --- 1. PAYMENT GATEWAY JOBS (PAYMENTS Queue) ---
  INITIALIZE_CHECKOUT_PAYMENT = 'INITIALIZE_CHECKOUT_PAYMENT',
  INITIALIZE_SUBSCRIPTION_PAYMENT = 'INITIALIZE_SUBSCRIPTION_PAYMENT', 
  VERIFY_PAYMENT_WEBHOOK = 'VERIFY_PAYMENT_WEBHOOK',
  
  // --- 2. BILLING & SUBSCRIPTION JOBS (BILLING/ANALYTICS Queue) ---
  SYNC_SUBSCRIPTION_STATUS = 'SYNC_SUBSCRIPTION_STATUS', 
  HANDLE_EXPIRY_REMINDERS = 'HANDLE_EXPIRY_REMINDERS',
  HANDLE_TENANT_SUSPENSIONS = 'HANDLE_TENANT_SUSPENSIONS',
  NOTIFY_PLAN_CHANGE = 'NOTIFY_PLAN_CHANGE', 

  // --- 3. ORDER & FULFILLMENT JOBS (ORDER_PROCESSING Queue) ---
  PROCESS_VENDOR_ORDER = 'PROCESS_VENDOR_ORDER',
  SYNC_PAYMENT_STATUS = 'SYNC_PAYMENT_STATUS', 
  SYNC_ANALYTICS = 'SYNC_ANALYTICS',
  
  // --- 4. NOTIFICATION JOBS (NOTIFICATIONS Queue) ---
  SEND_WELCOME_EMAIL = 'SEND_WELCOME_EMAIL',
  PROCESS_ORDER_RECEIPT = 'PROCESS_ORDER_RECEIPT',
  SEND_PAYMENT_CONFIRMATION = 'SEND_PAYMENT_CONFIRMATION',
  NOTIFY_MERCHANT_NEW_ORDER = 'NOTIFY_MERCHANT_NEW_ORDER',
  SEND_SUBSCRIPTION_RECEIPT = 'SEND_SUBSCRIPTION_RECEIPT', 

  // --- 5. SYSTEM TASKS ---
  PROCESS_IMAGE_OPTIMIZATION = 'PROCESS_IMAGE_OPTIMIZATION',
}