export enum QUEUES {
  NOTIFICATIONS = 'NOTIFICATIONS',
  ORDER_PROCESSING = 'ORDER_PROCESSING',
  PAYMENTS = 'PAYMENTS',
  ANALYTICS = 'ANALYTICS',
  DATA_IMPORT = 'DATA_IMPORT',
  IMAGE_PROCESSING = 'IMAGE_PROCESSING',
}

export enum JOB_NAMES {
  
  // Order Operations
  PROCESS_VENDOR_ORDER = 'PROCESS_VENDOR_ORDER',
  SYNC_ANALYTICS = 'SYNC_ANALYTICS',
  
  // Payments
  INITIALIZE_CHECKOUT_PAYMENT = 'INITIALIZE_CHECKOUT_PAYMENT',
  VERIFY_PAYMENT_WEBHOOK = 'VERIFY_PAYMENT_WEBHOOK',
  SYNC_PAYMENT_STATUS = 'SYNC_PAYMENT_STATUS', 
  
  // Notifications
  SEND_WELCOME_EMAIL = 'SEND_WELCOME_EMAIL',
  PROCESS_ORDER_RECEIPT = 'PROCESS_ORDER_RECEIPT',
  NOTIFY_MERCHANT_NEW_ORDER = 'NOTIFY_MERCHANT_NEW_ORDER',

}